M48
; DRILL file {KiCad 7.0.5-0} date 2023 June 09, Friday 10:40:50
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-06-09T10:40:50+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5-0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1378
%
G90
G05
T1
X3.1693Y-2.3228
X3.1693Y-4.2717
X5.4528Y-2.3228
X5.4528Y-4.2717
T2
X3.7731Y-4.2363
X5.4017Y-2.6077
T0
M30
